/// Flutter icons MiddaraDice
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MiddaraDice
///      fonts:
///       - asset: fonts/MiddaraDice.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MiddaraDiceIcons {
  MiddaraDiceIcons._();

  static const _kFontFam = 'MiddaraDice';
  static const String? _kFontPkg = null;

  static const IconData book =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burst =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skull =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
